// src/Page-Components/Login/Login.jsx
/* eslint-disable no-unused-vars */
import { useEffect, useState } from 'react';
import { EncryptionDecryption } from '../../Common/EncryptionDecryption';
import { Environment } from '../../Environment/Environment';
import { get_ip_address, redirect_to_home } from '../../Common/Utils';
import { AuthenticationService } from '../../Service/AuthenticationService';
import google from '../../../public/Images/google.svg';
import './Login.css';
import AlertModal from '../Common-Components/AlertModal/AlertModal';
import { useNavigate } from 'react-router-dom';

let loadAlertModal = null;
let api_response_status = null;

function Login() {
  const navigate = useNavigate();

  const JWT = localStorage.getItem("JWT");

  const [showAlertModal, setShowAlertModal] = useState(false);
  const [headerTextOfAlertModal, setHeaderTextOfAlertModal] = useState(null);
  const [bodyTextOfAlertModal, setBodyTextOfAlertModal] = useState(null);
  const [colorOfAlertModal, setColorOfAlertModal] = useState('green');


  const encryptionDecryption = new EncryptionDecryption();
  const authenticationService = new AuthenticationService();


  useEffect(() => {
    if (JWT !== undefined && JWT !== null) {
      redirect_to_home(navigate);
    }

    const signUpButton = document.getElementById('signUp');
    const signInButton = document.getElementById('signIn');
    const container = document.getElementById('login_child_container');

    signUpButton.addEventListener('click', () => {
      container.classList.add("right-panel-active");
    });

    signInButton.addEventListener('click', () => {
      container.classList.remove("right-panel-active");
    });
  }, []);


  function ValidateSignUpFormData(first_name, last_name, email, password, confirm_password) {
    let validationStatus = true;
    let warning_message = "";

    if (first_name === "" || first_name === null) {
      warning_message = "Firstname can't be empty.";
      validationStatus = false;
    } else if (last_name === "" || last_name === null) {
      warning_message = "Lastname can't be empty.";
      validationStatus = false;
    } else if (email === "" || email === null) {
      warning_message = "Email can't be empty.";
      validationStatus = false;
    } else if (password === "" || password === null) {
      warning_message = "Password can't be empty.";
      validationStatus = false;
    } else if (confirm_password === "" || confirm_password === null) {
      warning_message = "Confirm Password can't be empty.";
      validationStatus = false;
    } else if (password !== confirm_password) {
      warning_message = "Password and Confirm password is not matching.";
      validationStatus = false;
    }

    if (validationStatus === false) {
      Alert(Environment.alert_modal_header_signup, Environment.colorWarning, warning_message);
    }

    return validationStatus;
  }


  async function DoSignUp() {
    api_response_status = null;

    let first_name = document.getElementById("signup_firstname").value;
    let last_name = document.getElementById("signup_lastname").value;
    let email = document.getElementById("signup_email").value;
    let password = document.getElementById("signup_password").value;
    let confirm_password = document.getElementById("signup_confirm_password").value;

    if (ValidateSignUpFormData(first_name, last_name, email, password, confirm_password) === false) return;

    let obj = {
      first_name: first_name,
      last_name: last_name,
      email: email,
      password: encryptionDecryption.Encrypt(password),
    };

    let response = await authenticationService.DoSignUpService(obj);
    api_response_status = response.status;

    if (api_response_status === 200) {
      Alert(Environment.alert_modal_header_signup, Environment.colorSuccess, response.message);

      document.getElementById("signup_firstname").value = null;
      document.getElementById("signup_lastname").value = null;
      document.getElementById("signup_email").value = null;
      document.getElementById("signup_password").value = null;
      document.getElementById("signup_confirm_password").value = null;
    } else {
      Alert(Environment.alert_modal_header_signup, Environment.colorError, response.message);
    }
  }


  function ValidateLoginFormData(email, password) {
    let validationStatus = true;
    let warning_message = "";

    if (email === "" || email === null) {
      warning_message = "Email can't be empty.";
      validationStatus = false;
    } else if (password === "" || password === null) {
      warning_message = "Password can't be empty.";
      validationStatus = false;
    }

    if (validationStatus === false) {
      Alert(Environment.alert_modal_header_login, Environment.colorWarning, warning_message);
    }

    return validationStatus;
  }


  async function DoLogin() {
    api_response_status = null;

    let email = document.getElementById("login_email").value;
    let password = document.getElementById("login_password").value;

    if (ValidateLoginFormData(email, password) === false) return;

    let obj = {
      email: email,
      password: encryptionDecryption.Encrypt(password),
      ip_address: await get_ip_address()
    };

    let response = await authenticationService.DoLoginService(obj);
    api_response_status = response.status;

    if (api_response_status !== 200) {
      Alert(Environment.alert_modal_header_login, Environment.colorError, response.message);
    } else {
      localStorage.removeItem("JWT");
      localStorage.setItem("JWT", JSON.stringify(response.data));
      redirect_to_home(navigate);
    }
  }


  function Alert(header, color, message) {
    closeAlertModal();

    setColorOfAlertModal(color);
    openAlertModal(header, message);

    loadAlertModal = setTimeout(() => {
      closeAlertModal();
    }, 5000);
  }


  function openAlertModal(header_text, body_text) {
    setHeaderTextOfAlertModal(header_text);
    setBodyTextOfAlertModal(body_text);
    setShowAlertModal(true);
  }


  function closeAlertModal() {
    setShowAlertModal(false);
    setHeaderTextOfAlertModal(null);
    setBodyTextOfAlertModal(null);

    clearTimeout(loadAlertModal);
    loadAlertModal = null;

    if (api_response_status === 200) {
      if (document.getElementById('signIn')) {
        document.getElementById('signIn').click();
      }
      api_response_status = null;
    }
  }


  return (
    <>
      <div className='login-container'>
        <AlertModal showModal={showAlertModal} handleClose={closeAlertModal} headerText={headerTextOfAlertModal} bodyText={bodyTextOfAlertModal} alertColor={colorOfAlertModal} />

        <div className="login-child-container" id="login_child_container">
          <div className="form-container sign-up-container">

            <div className='form-div'>
              <h1>Create Account</h1>

              <div className="social-container">
                <a href="#" className="social"><img src={google}></img></a>
              </div>
              <span>or use your email for registration</span>

              <input type="text" placeholder="First Name" id="signup_firstname" />
              <input type="text" placeholder="Last Name" id="signup_lastname" />
              <input type="email" placeholder="Email" id="signup_email" />
              <input type="password" placeholder="Password" id="signup_password" />
              <input type="password" placeholder="Confirm Password" id="signup_confirm_password" />

              <button className="signup_btn loginPageButtons" onClick={DoSignUp}>Sign Up</button>
            </div>
          </div>

          <div className="form-container sign-in-container">
            <div className='form-div'>
              <h1>Sign in</h1>

              <div className="social-container">
                <a href="#" className="social"><img src={google}></img></a>
              </div>
              <span>or use your account</span>

              <input type="email" placeholder="Email" id="login_email" />
              <input type="password" placeholder="Password" id="login_password" />

              <a href="#">Forgot your password?</a>
              <button onClick={DoLogin} className='loginPageButtons'>Sign In</button>
            </div>
          </div>

          <div className="overlay-container">
            <div className="overlay">
              <div className="overlay-panel overlay-left">
                <h1>Welcome Back!</h1>
                <p>To keep connected with us please login with your personal info</p>
                <button className="loginPageButtons ghost" id="signIn">Sign In</button>
              </div>
              <div className="overlay-panel overlay-right">
                <h1>Hello, Friend!</h1>
                <p>Enter your personal details and start journey with us</p>
                <button className="loginPageButtons ghost" id="signUp">Sign Up</button>
              </div>
            </div>

          </div>
        </div>
      </div>
    </>
  )
}

export default Login;

// src/app/login/login.component.ts
// login.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { EncryptionDecryption } from '../utility/encryption-decryption';
import { AuthenticationService } from '../service/authentication/authentication.service';
import { Environment } from '../constants/environment';
import { get_ip_address, redirect_to_home } from '../utility/common-utils';
import { CommonModule } from '@angular/common';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { CustomAlertComponent } from '../common-component/custom-alert/custom-alert.component';
import { ResponseTypeColor } from '../constants/common-constants';

@Component({
  selector: 'app-login',
  imports: [CommonModule, FormsModule, MatDialogModule],
  standalone: true,
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  readonly dialog = inject(MatDialog);
  login = { email: '', password: '' };
  signUp = { firstName: '', lastName: '', email: '', password: '', confirmPassword: '' };

  showAlertModal = false;
  headerTextOfAlertModal: string | null = null;
  bodyTextOfAlertModal: string | null = null;
  colorOfAlertModal = 'green';

  private loadAlertModal: any;
  private apiResponseStatus: number | null = null;

  private encryptionDecryption: EncryptionDecryption = new EncryptionDecryption();

  constructor(
    private router: Router,
    private authService: AuthenticationService,
  ) { }

  ngOnInit(): void {
    const JWT = localStorage.getItem("JWT");
    if (JWT) {
      redirect_to_home(this.router);
    }
  }

  togglePanel(signUp: boolean) {
    const container = document.getElementById('login_child_container');
    if (signUp) container?.classList.add("right-panel-active");
    else container?.classList.remove("right-panel-active");
  }

  validateSignUp(): boolean {
    const { firstName, lastName, email, password, confirmPassword } = this.signUp;

    if (!firstName) {
      this.openDialog('SignUp', "Firstname can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (!lastName) {
      this.openDialog('SignUp', "Lastname can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (!email) {
      this.openDialog('SignUp', "Email can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (!password) {
      this.openDialog('SignUp', "Password can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (!confirmPassword) {
      this.openDialog('SignUp', "Confirm Password can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (password !== confirmPassword) {
      this.openDialog('SignUp', "Password and Confirm password is not matching.", ResponseTypeColor.INFO, null);
      return false;
    }
    
    return true;
  }

  async doSignUp() {
    if (!this.validateSignUp()) return;

    // const { firstName, lastName, email, password } = this.signUp;
    // const encryptedPassword = this.encryption.Encrypt(password);
    // const response = await this.authService.doSignUpService({ first_name: firstName, last_name: lastName, email, password: encryptedPassword });
    // this.apiResponseStatus = response.status;

    // if (response.status === 200) {
    //   this.alert(response.message, Environment.colorSuccess, Environment.alert_modal_header_signup);
    //   this.signUp = { firstName: '', lastName: '', email: '', password: '', confirmPassword: '' };
    // } else {
    //   this.alert(response.message, Environment.colorError, Environment.alert_modal_header_signup);
    // }
  }

  validateLogin(): boolean {
    const { email, password } = this.login;
    if (!email) {
      this.openDialog('Login', "Email can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    if (!password) {
      this.openDialog('Login', "Password can't be empty.", ResponseTypeColor.INFO, null);
      return false;
    }
    return true;
  }

  async doLogin() {
    if (!this.validateLogin()) return;

    // const ip = await get_ip_address();
    // const encryptedPassword = this.encryption.Encrypt(this.login.password);
    // const response = await this.authService.doLoginService({ email: this.login.email, password: encryptedPassword, ip_address: ip });
    // this.apiResponseStatus = response.status;

    // if (response.status === 200) {
    //   localStorage.setItem("JWT", JSON.stringify(response.data));
    //   redirectToHome(this.router);
    // } else {
    //   this.alert(response.message, Environment.colorError, Environment.alert_modal_header_login);
    // }
  }

  openDialog(dialogTitle: string, dialogText: string, dialogType: number, navigateRoute: string | null): void {
    const dialogRef = this.dialog.open(CustomAlertComponent, {
      data: { title: dialogTitle, text: dialogText, type: dialogType }
    });

    dialogRef.afterClosed().subscribe(() => {
      if (navigateRoute) {
        window.location.href = navigateRoute;
      }
    });
  }
}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row" [ngClass]="{ 'flex-row-reverse': isSignUpActive }">

                <!-- Sign Up Form -->
                <div class="col-md-6 bg-light p-4 rounded">
                    <h2 class="mb-3">Create Account</h2>
                    <div class="mb-3 text-center">
                        <a href="#" class="btn btn-outline-secondary btn-sm">
                            <img [src]="'assets/images/google.svg'" alt="Google" height="20"> Sign up with Google
                        </a>
                    </div>
                    <p class="text-center">or use your email for registration</p>
                    <form>
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="First Name"
                                [(ngModel)]="signUp.firstName" name="signupFirstName">
                        </div>
                        <div class="mb-3">
                            <input type="text" class="form-control" placeholder="Last Name"
                                [(ngModel)]="signUp.lastName" name="signupLastName">
                        </div>
                        <div class="mb-3">
                            <input type="email" class="form-control" placeholder="Email" [(ngModel)]="signUp.email"
                                name="signupEmail">
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Password"
                                [(ngModel)]="signUp.password" name="signupPassword">
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Confirm Password"
                                [(ngModel)]="signUp.confirmPassword" name="signupConfirmPassword">
                        </div>
                        <button type="button" class="btn btn-primary w-100" (click)="DoSignUp()">Sign Up</button>
                    </form>
                </div>

                <!-- Sign In Form -->
                <div class="col-md-6 bg-white p-4 rounded shadow-sm">
                    <h2 class="mb-3">Sign In</h2>
                    <div class="mb-3 text-center">
                        <a href="#" class="btn btn-outline-secondary btn-sm">
                            <img src="assets/images/google.svg" alt="Google" height="20"> Sign in with Google
                        </a>
                    </div>
                    <p class="text-center">or use your account</p>
                    <form>
                        <div class="mb-3">
                            <input type="email" class="form-control" placeholder="Email" [(ngModel)]="login.email"
                                name="loginEmail">
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" placeholder="Password"
                                [(ngModel)]="login.password" name="loginPassword">
                        </div>
                        <div class="mb-3 text-end">
                            <a href="#">Forgot your password?</a>
                        </div>
                        <button type="button" class="btn btn-success w-100" (click)="doLogin()">Sign In</button>
                    </form>
                </div>

            </div>

            <!-- Overlay buttons -->
            <div class="text-center mt-4">
                <p>Toggle between forms:</p>
                <button class="btn btn-outline-primary me-2" (click)="togglePanel(false)">Show Sign In</button>
                <button class="btn btn-outline-secondary" (click)="togglePanel(true)">Show Sign Up</button>
            </div>
        </div>
    </div>
</div>
