// src/app/page-component/manage-video/edit-video/edit-video.component.ts
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { UploadService } from '../../../service/upload/upload.service';
import { Environment } from '../../../constants/environment';
import { CommonModule, Location } from '@angular/common';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { CustomAlertComponent } from '../../../common-component/custom-alert/custom-alert.component';
import { ResponseTypeColor } from '../../../constants/common-constants';
import { FormsModule } from '@angular/forms';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faTrash } from '@fortawesome/free-solid-svg-icons';
import { base64toImage } from '../../../utility/common-utils';

@Component({
  selector: 'app-edit-video',
  imports: [CommonModule, FormsModule, MatDialogModule, MatProgressBarModule, FontAwesomeModule],
  standalone: true,
  templateUrl: './edit-video.component.html',
  styleUrls: ['./edit-video.component.css']
})
export class EditVideoComponent implements OnInit {
  readonly dialog = inject(MatDialog);
  matProgressBarVisible = false;

  maxCharacterTitle = 100;
  maxCharacterDescription = 5000;

  faTrash = faTrash;

  t_video_info_id: any;
  guid: string = '';
  video_title: string = '';
  old_thumbnail: string = '';
  video_description: string = '';
  is_public: number = 0;

  new_thumbnail: File | null = null;
  new_thumbnail_base64: string | null = null;
  thumbnail_name: string = '';
  video_pubblicity_status = 0;

  edited_video_title: string = '';
  edited_video_description: string = '';

  showAlertModal = false;
  headerTextOfAlertModal: string | null = null;
  bodyTextOfAlertModal: string | null = null;
  colorOfAlertModal: string = 'green';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private uploadService: UploadService,
    private location: Location,
    private cdr: ChangeDetectorRef
  ) { }

  ngOnInit(): void {
    const state = history.state;
    this.t_video_info_id = state.t_video_info_id;
    this.guid = state.guid;
    this.video_title = state.video_title;
    this.old_thumbnail = state.old_thumbnail;
    this.video_description = state.video_description;
    this.is_public = state.is_public;

    this.edited_video_title = this.video_title;
    this.edited_video_description = this.video_description;
    this.video_pubblicity_status = this.is_public;
  }

  handleVideoStatusToggleSwitch() {
    this.video_pubblicity_status = this.video_pubblicity_status === 0 ? 1 : 0;
  }

  thumbnailSave(event: Event): void {
    debugger;
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) return;

    const file = input.files[0];
    this.new_thumbnail = file;
    this.thumbnail_name = file.name;

    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      const base64Raw = result.split(',')[1]; // Get base64 without metadata
      this.new_thumbnail_base64 = base64toImage(base64Raw);
    };

    reader.readAsDataURL(file);
  }

  removeThumbnail(event: Event) {
    event.preventDefault();
    this.new_thumbnail = null;
    this.thumbnail_name = '';
  }

  openAlertModal(header: string, body: string, color: string) {
    this.headerTextOfAlertModal = header;
    this.bodyTextOfAlertModal = body;
    this.colorOfAlertModal = color;
    this.showAlertModal = true;

    setTimeout(() => {
      this.showAlertModal = false;
      this.router.navigate(['/manage/uploaded-video']);
    }, 5000);
  }

  async saveVideoInfo() {
    const formData = new FormData();
    formData.append('t_video_info_id', this.t_video_info_id);
    formData.append('guid', this.guid);
    formData.append('title', this.edited_video_title);
    formData.append('description', this.edited_video_description);
    formData.append('is_public', this.video_pubblicity_status.toString());
    if (this.new_thumbnail) {
      formData.append('thumbnail', this.new_thumbnail);
    }

    this.activeMatProgressBar();

    try {
      this.uploadService.DoUpdateVideoInfo(formData)
        .subscribe({
          next: (result: any) => {
            this.hideMatProgressBar();

            if (result.status === 200) {
              this.openDialog('Upload', result.message, ResponseTypeColor.SUCCESS, null);
            } else {
              this.openDialog('Upload', result.message, ResponseTypeColor.ERROR, null);
            }
          },
          error: () => {
            this.hideMatProgressBar();
            this.openDialog('Upload', "Failed to upload video info.", ResponseTypeColor.ERROR, null);
          }
        });
    } catch (error) {
      this.hideMatProgressBar();
      this.openDialog('Upload', "Failed to upload video info.", ResponseTypeColor.ERROR, null);
    }
  }

  goBack() {
    this.location.back();
  }

  activeMatProgressBar() {
    this.matProgressBarVisible = true;
    this.cdr.detectChanges();
  }

  hideMatProgressBar() {
    this.matProgressBarVisible = false;
    this.cdr.detectChanges();
  }

  openDialog(dialogTitle: string, dialogText: string, dialogType: number, navigateRoute: string | null): void {
    const dialogRef = this.dialog.open(CustomAlertComponent, {
      data: { title: dialogTitle, text: dialogText, type: dialogType }
    });

    dialogRef.afterClosed().subscribe(() => {
      if (navigateRoute) {
        window.location.href = navigateRoute;
      }
    });
  }
}

<mat-progress-bar mode="indeterminate" *ngIf="matProgressBarVisible" class="matProgressBar"></mat-progress-bar>

<div class="container">
  <h3 class="text-muted mb-3 container_header">Edit - {{ video_title }}</h3>

  <!-- Title -->
  <div class="mb-4">
    <label class="form-label fw-semibold">Video Title<span class="text-danger">*</span></label>
    <div class="input-group">
      <input type="text" class="form-control" maxlength="{{ maxCharacterTitle }}" [(ngModel)]="edited_video_title" />
    </div>
    <small class="form-text text-muted">{{ edited_video_title.length }}/{{ maxCharacterTitle }}</small>
  </div>

  <!-- Description -->
  <div class="mb-4">
    <label class="form-label fw-semibold">Video Description<span class="text-danger">*</span></label>
    <div class="input-group">
      <textarea class="form-control" rows="5" maxlength="{{ maxCharacterDescription }}"
        [(ngModel)]="edited_video_description"></textarea>
    </div>
    <small class="form-text text-muted">{{ edited_video_description.length }}/{{ maxCharacterDescription }}</small>
  </div>

  <!-- Thumbnail and Save -->
  <div class="d-flex flex-column flex-md-row justify-content-between gap-4">

    <!-- Thumbnail Upload -->
    <div class="border border-dashed rounded p-3 text-center w-100">
      <div *ngIf="!new_thumbnail">
        <p class="fw-bold text-muted">Drop thumbnail here</p>
        <p class="text-muted">or</p>
      </div>

      <div *ngIf="!new_thumbnail && old_thumbnail" class="w-100 d-flex flex-column align-items-center gap-2">
        <img [src]="old_thumbnail" class="img-fluid rounded mb-3 w-25" />
      </div>

      <div *ngIf="new_thumbnail" class="w-100 d-flex flex-column align-items-center gap-2">
        <img [src]="new_thumbnail_base64" class="img-fluid rounded mb-3 w-25" />
      </div>

      <input type="file" accept=".jpg, .jpeg, image/jpeg" (change)="thumbnailSave($event)" *ngIf="!new_thumbnail"
        class="form-control w-auto mx-auto" />

      <div *ngIf="new_thumbnail" class="d-flex flex-column align-items-center gap-2">
        <span class="text-success">{{thumbnail_name}}</span>
        <div class="d-flex flex-row-reverse w-100">
          <button class="btn btn-outline-secondary btn-sm" (click)="removeThumbnail($event)">
            <fa-icon [icon]="faTrash"></fa-icon>
            Remove
          </button>
        </div>
      </div>
    </div>

    <!-- Visibility and Save -->
    <div class="d-flex flex-column align-items-center border border-dashed rounded p-3 gap-3 w-100">
      <label class="fw-semibold">Visibility Status</label>
      <div class="form-check form-switch">
        <input type="checkbox" class="form-check-input" id="video_status_toggle"
          (change)="handleVideoStatusToggleSwitch()" [checked]="video_pubblicity_status === 1" />
        <label class="form-check-label" for="video_status_toggle">
          {{ video_pubblicity_status === 1 ? 'Public' : 'Private' }}
        </label>
      </div>

      <button type="button" class="btn btn-primary btn-sm" (click)="saveVideoInfo()">Save</button>
    </div>
  </div>

  <!-- Back Button -->
  <div class="mt-4">
    <button type="button" class="btn btn-outline-secondary btn-sm" (click)="goBack()">Go Back</button>
  </div>
</div>

// src/Page-Components/Manage-Video/Edit-Video/EditVideo.jsx
import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useNavigate } from 'react-router-dom';
import { go_back } from '../../../Common/Utils';
import removeFile from '../../../../public/Images/remove-file.svg';
import './EditVideo.css';
import { UploadService } from '../../../Service/UploadService';
import { Environment } from '../../../Environment/Environment';
import AlertModal from '../../Common-Components/AlertModal/AlertModal';


let loadAlertModal = null;
function EditVideo() {
    const location = useLocation();
    const navigate = useNavigate();
    const { t_video_info_id, guid, video_title, old_thumbnail, video_description, is_public, uploaded_at, processing_status } = location.state;

    const [max_character_title, set_max_character_title] = useState(100);
    const [max_character_description, set_max_character_description] = useState(5000);

    const [new_thumbnail, set_new_thumbnail] = useState(null);
    const [thumbnail_name, set_thumbnail_name] = useState("");
    const [video_pubblicity_status, set_video_pubblicity_status] = useState(0);
    const [edited_video_title, set_edited_video_title] = useState("");
    const [edited_video_description, set_edited_video_description] = useState("");

    const [showAlertModal, setShowAlertModal] = useState(false);
    const [headerTextOfAlertModal, setHeaderTextOfAlertModal] = useState(null);
    const [bodyTextOfAlertModal, setBodyTextOfAlertModal] = useState(null);
    const [colorOfAlertModal, setColorOfAlertModal] = useState('green');

    const uploadService = new UploadService();

    useEffect(() => {
        set_edited_video_title(video_title);
        set_edited_video_description(video_description);
        if (is_public === 1) handleVideoStatusToggleSwitch();
    }, [])


    function handleVideoStatusToggleSwitch() {
        const toggle = document.getElementById('video_status_toggle');

        toggle.classList.toggle('toggle-right');

        if (video_pubblicity_status === 0) {
            set_video_pubblicity_status(1);
        } else {
            set_video_pubblicity_status(0);
        }
    }


    function thumbnailSave(event) {
        const file = event.target.files[0];
        if (file) {
            set_thumbnail_name(file.name);
            set_new_thumbnail(file);
        }
    }


    function removeThumbnail() {
        event.preventDefault();
        set_new_thumbnail(null);
        set_thumbnail_name("");
    }


    function Alert(header, color, message) {
        if (loadAlertModal) closeAlertModal();

        setColorOfAlertModal(color);
        openAlertModal(header, message);

        loadAlertModal = setTimeout(() => {
            closeAlertModal();
            navigate("/manage/uploaded-video");
        }, 5000);
    }


    function openAlertModal(header_text, body_text) {
        setHeaderTextOfAlertModal(header_text);
        setBodyTextOfAlertModal(body_text);
        setShowAlertModal(true);
    }


    function closeAlertModal() {
        setShowAlertModal(false);
        setHeaderTextOfAlertModal(null);
        setBodyTextOfAlertModal(null);

        clearTimeout(loadAlertModal);
        loadAlertModal = null;
        navigate("/manage/uploaded-video");
    }


    async function saveVideoInfo() {
        let title = document.getElementById("video_title").value;
        let description = document.getElementById("video_description").value;

        let formData = new FormData();
        formData.append("t_video_info_id", t_video_info_id);
        formData.append("guid", guid);
        formData.append("title", title);
        formData.append("description", description);
        formData.append("is_public", parseInt(video_pubblicity_status));
        formData.append("thumbnail", new_thumbnail);

        try {
            let response = await uploadService.DoUpdateVideoInfo(formData);
            console.log(response)

            if (response.status == 200) {
                Alert(Environment.alert_modal_header_video_info_update, Environment.colorSuccess, response.message);
            } else {
                Alert(Environment.alert_modal_header_video_info_update, Environment.colorError, response.message);
            }
        } catch (error) {
            console.error("Error:", error);
            Alert(Environment.alert_modal_header_video_info_update, Environment.colorError, "Failed to upload video info.");
        }
    }


    return (
        <>
            <div className='container-upload '>
                <h1>Edit - {video_title}</h1>

                <AlertModal showModal={showAlertModal} handleClose={closeAlertModal} headerText={headerTextOfAlertModal} bodyText={bodyTextOfAlertModal} alertColor={colorOfAlertModal} />

                <div className='title'>
                    <span>Title<span className="required_color">*</span></span>
                    <div className="input-container">
                        <input
                            type="text"
                            className="upload_input upload_normal_input"
                            id="video_title"
                            maxLength={max_character_title}
                            value={edited_video_title}
                            onChange={(e) => set_edited_video_title(e.target.value)}
                        />
                        <span id="charCountTitle">{edited_video_title.length}/{max_character_title}</span>
                    </div>
                </div>

                <div className='description'>
                    <span>Description<span className="required_color">*</span></span>
                    <div className="input-container">
                        <textarea
                            className="upload_input upload_textarea"
                            rows="10"
                            id="video_description"
                            value={edited_video_description}
                            onChange={(e) => set_edited_video_description(e.target.value)}>
                            maxLength={max_character_description}
                        </textarea>
                        <span id="charCountDescription">{edited_video_description.length}/{max_character_description}</span>
                    </div>

                </div>

                <div className='thumbnail_and_save'>
                    <label className="drop-container-thumbnail" id="dropcontainer">
                        <div className='drop-container-info'>
                            <div className='drop-container-info-text'>
                                {!new_thumbnail && <span className="drop-title">Drop thumbnail here</span>}
                                {!new_thumbnail && <span className="drop-or-text">or</span>}
                            </div>
                            {!new_thumbnail && old_thumbnail && <div className='old_thumbnail'>
                                <img src={old_thumbnail} />
                            </div>}
                        </div>
                        {!new_thumbnail && <input type="file" accept="image/*" onChange={thumbnailSave} required />}
                        {new_thumbnail && <span className="drop-filename-text">{thumbnail_name}</span>}
                        {new_thumbnail && <span className='remove_thumbnail_btn'><img src={removeFile} className='menu-icons' onClick={removeThumbnail}></img></span>}
                    </label>

                    <div className='video_right_side_buttons'>
                        <div className='video_publicity_switch_container'>
                            <span className='video_publicity_name'>Private</span>
                            <div className='video_publicity_switch' onClick={handleVideoStatusToggleSwitch}>
                                <div id='video_status_toggle'></div>
                            </div>
                            <span className='video_publicity_name'>Public</span>
                        </div>

                        <button className='video-save-button' onClick={saveVideoInfo}>Save</button>
                    </div>
                </div>

                <button className='back-button' onClick={() => go_back(navigate)}>Go Back</button>
            </div>
        </>
    );
}

export default EditVideo;
