// src/Layout/Layout.jsx
import React from 'react';
import './Layout.css';
import { Outlet } from "react-router-dom";
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { DashboardService } from '../Service/DashboardService';
import { GenerateMenu } from '../Common/MenuGenerator';

import bars from '../../public/Images/bars.svg';
import home from '../../public/Images/home.svg';
import dashboard from '../../public/Images/dashboard.svg';
import upload from '../../public/Images/upload.svg';
import profile from '../../public/Images/profile.svg';
import logout from '../../public/Images/logout.svg';
import manage from '../../public/Images/manage.svg';
import uploaded_video from '../../public/Images/uploaded_video.svg';
import deleted_video from '../../public/Images/delete.svg';
import down_arrow from '../../public/Images/down_arrow.svg';

function Layout() {
    const navigate = useNavigate();

    const [windowWidth, setWindowWidth] = useState(window.innerWidth);
    const [previousWindowWidth, setPreviousWindowWidth] = useState(window.innerWidth);
    const [toogleStatus, setToogleStatus] = useState(0);
    const [elements, setElements] = useState([]);
    const [layout, setLayout] = useState([]);

    const dashboardService = new DashboardService();


    const iconMap = {
        home: home,
        dashboard: dashboard,
        upload: upload,
        profile: profile,
        logout: logout,
        manage: manage,
        uploaded_video: uploaded_video,
        deleted_video: deleted_video,
        down_arrow: down_arrow
    };


    useEffect(() => {
        getLeftSideMenu();
    }, []);


    async function getLeftSideMenu() {
        try {
            let response = await dashboardService.DoGetMenu();
            setLayout(response.data);

            const newElements = response.data.map(item => ({
                id: item.id,
                menu_name_id: item.menu_name_id
            }));
            setElements(newElements);

            document.getElementById("root_menu").innerHTML = GenerateMenu(response.data, iconMap);
        } catch (error) {
            console.error("Error:", error);
            Alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, "Failed to upload video info.");
        }
    }


    window.toggleSubmenu = function (id, parent_id, route) {
        if (parent_id !== -1) navigate(route);

        const subMenuParent = document.getElementById(`submenu-${id}`);
        const subMenuToggleIcon = document.getElementById(`toggle-${id}`);
        const subMenus = document.getElementsByClassName('a-menu-item-child');

        if (subMenuParent.style.maxHeight && subMenuParent.style.maxHeight !== "0px") {
            subMenuParent.style.maxHeight = "0px";
            subMenuToggleIcon.style.transform = "rotate(0deg)";
        } else {
            subMenuParent.style.maxHeight = subMenuParent.scrollHeight + "px";
            subMenuToggleIcon.style.transform = "rotate(180deg)";
        }

        let subMenuMarginLeft = (document.getElementById('menubar').style.width === '70px') ? "0px" : "20px";

        for (let i = 0; i < subMenus.length; i++) {
            subMenus[i].style.marginLeft = subMenuMarginLeft;
        }
    };


    window.navigateTo = function (route) {
        navigate(route);
    }


    function toggleSidebar() {
        if (windowWidth < 1200) return;

        const menubar = document.getElementById('menubar');
        var subMenus = document.getElementsByClassName('a-menu-item-child');

        let newWidthMenubar, newWidthMainContent, newDisplay, marginLeftSubmenu;
        if (document.getElementById('menubar').style.width === '70px') {
            newWidthMenubar = '13%';
            newWidthMainContent = '86%';
            newDisplay = 'block';
            marginLeftSubmenu = "20px";
            setToogleStatus(1);
        } else {
            newWidthMenubar = '70px';
            newWidthMainContent = 'calc(100% - 85px)';
            newDisplay = 'none';
            marginLeftSubmenu = "0px";
            setToogleStatus(0);
        }

        menubar.style.width = newWidthMenubar;

        const mainContent = document.getElementById("mainContent");
        if (mainContent) mainContent.style.width = newWidthMainContent;

        elements.forEach((item) => {
            const elem = document.getElementById(item.menu_name_id);
            if (elem) elem.style.display = newDisplay;
            let toggleMenuIcon = document.getElementById(`toggle-${item.id}`);
            if (toggleMenuIcon) toggleMenuIcon.style.display = newDisplay;
        });

        for (let i = 0; i < subMenus.length; i++) {
            subMenus[i].style.marginLeft = marginLeftSubmenu;
        }
    }


    useEffect(() => {
        const handleResize = () => {
            setWindowWidth(window.innerWidth);
        };

        window.addEventListener("resize", handleResize);

        return () => {
            window.removeEventListener("resize", handleResize);
        };
    }, []);


    useEffect(() => {
        const menubar = document.getElementById("menubar");
        let newWidthMenubar, newWidthMainContent, newDisplay;

        if (windowWidth >= 1200) {
            if (previousWindowWidth >= 1200 || !toogleStatus) {
                setPreviousWindowWidth(windowWidth);
                return;
            }
            newWidthMenubar = "13%";
            newWidthMainContent = "86%";
            newDisplay = "block";
        } else {
            if (previousWindowWidth < 1200) {
                setPreviousWindowWidth(windowWidth);
                return;
            }
            newWidthMenubar = '70px';
            newWidthMainContent = 'calc(100% - 85px)';
            newDisplay = "none";
        }

        if (menubar) menubar.style.width = newWidthMenubar;

        elements.forEach((id) => {
            const elem = document.getElementById(id);
            if (elem) elem.style.display = newDisplay;
        });

        const mainContent = document.getElementById("mainContent");
        if (mainContent) mainContent.style.width = newWidthMainContent;

        setPreviousWindowWidth(windowWidth);
    }, [windowWidth]);


    return (
        <>
            <div className='navbar' id='navbar'>
                <img src={bars} className='menu-icons toggleMenu' onClick={toggleSidebar}></img>
                <p className='navbar-text'>Streamer</p>
            </div>

            <div className='mainBody' id='mainBody'>
                <div className='menubar' id='menubar'>
                    <div id="root_menu"></div>
                </div>

                <div id='mainContent' className='mainContent'>
                    <div className='mainContentActualPortion'>
                        <div className='mainContentActualPortionChild'>
                            <Outlet />
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Layout;

// src/app/layout/layout.component.ts
import { redirect_to_home } from '../utility/common-utils';
import { AuthenticationService } from '../service/authentication/authentication.service';
import { Component, OnInit, HostListener, ChangeDetectorRef, inject } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { DashboardService } from '../service/dashboard/dashboard.service';
import { ResponseTypeColor } from '../constants/common-constants';
import { GenerateMenu } from '../utility/menu-generator';
import { CustomAlertComponent } from '../common-component/custom-alert/custom-alert.component';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-layout',
  imports: [MatProgressBarModule, MatDialogModule, RouterModule, CommonModule],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent implements OnInit {
  matProgressBarVisible = false;
  readonly dialog = inject(MatDialog);

  windowWidth = window.innerWidth;
  previousWindowWidth = window.innerWidth;
  toogleStatus = 0;
  elements: any[] = [];
  layout: any[] = [];

  iconMap: { [key: string]: string } = {
    home: 'assets/images/home.svg',
    dashboard: 'assets/images/dashboard.svg',
    upload: 'assets/images/upload.svg',
    profile: 'assets/images/profile.svg',
    logout: 'assets/images/logout.svg',
    manage: 'assets/images/manage.svg',
    uploaded_video: 'assets/images/uploaded_video.svg',
    deleted_video: 'assets/images/delete.svg',
    down_arrow: 'assets/images/down_arrow.svg'
  };

  constructor(
    private authService: AuthenticationService,
    private dashboardService: DashboardService,
    private cdr: ChangeDetectorRef,
    private router: Router
  ) { }

  loadHomePage() {
    if (this.authService.getToken()) {
      redirect_to_home();
    }
  }

  ngOnInit(): void {
    this.getLeftSideMenu();
  }

  @HostListener('window:resize')
  onResize() {
    this.windowWidth = window.innerWidth;
    this.adjustLayout();
  }

  async getLeftSideMenu() {
    try {
      this.dashboardService.DoGetMenu().subscribe({
        next: (response) => {
          if (response.status === 200) {
            this.hideMatProgressBar();
            this.layout = response.data;
            console.log(this.layout)

            this.elements = response.data.map((item: any) => ({
              id: item.id,
              menu_name_id: item.menu_name_id
            }));

            const rootMenu = document.getElementById('root_menu');
            if (rootMenu) {
              rootMenu.innerHTML = GenerateMenu(response.data, this.iconMap);
            }
            return;
          }

          this.hideMatProgressBar();
          this.openDialog("Dashboard", response.message, ResponseTypeColor.ERROR, null);
        },
        error: (err) => {
          this.hideMatProgressBar();
          this.openDialog("Dashboard", "Internal server error", ResponseTypeColor.ERROR, null);
        }
      });
    } catch (error) {
      console.error('Error fetching menu', error);
      alert('Failed to load menu');
    }
  }

  toggleSidebar() {
    if (this.windowWidth < 1200) return;

    const menubar = document.getElementById('menubar');
    const subMenus = document.getElementsByClassName('a-menu-item-child') as HTMLCollectionOf<HTMLElement>;

    const isCollapsed = menubar?.style.width === '70px';
    const newWidthMenubar = isCollapsed ? '13%' : '70px';
    const newWidthMainContent = isCollapsed ? '86%' : 'calc(100% - 85px)';
    const newDisplay = isCollapsed ? 'block' : 'none';
    const marginLeftSubmenu = isCollapsed ? '20px' : '0px';
    this.toogleStatus = isCollapsed ? 1 : 0;

    if (menubar) menubar.style.width = newWidthMenubar;

    const mainContent = document.getElementById('mainContent');
    if (mainContent) mainContent.style.width = newWidthMainContent;

    this.elements.forEach(item => {
      const elem = document.getElementById(item.menu_name_id);
      if (elem) elem.style.display = newDisplay;
      const toggleMenuIcon = document.getElementById(`toggle-${item.id}`);
      if (toggleMenuIcon) toggleMenuIcon.style.display = newDisplay;
    });

    Array.from(subMenus).forEach(el => {
      el.style.marginLeft = marginLeftSubmenu;
    });
  }

  private adjustLayout() {
    const menubar = document.getElementById('menubar');
    const mainContent = document.getElementById('mainContent');
    const isWide = this.windowWidth >= 1200;

    if (isWide && (this.previousWindowWidth >= 1200 || !this.toogleStatus)) {
      this.previousWindowWidth = this.windowWidth;
      return;
    }

    if (!isWide && this.previousWindowWidth < 1200) {
      this.previousWindowWidth = this.windowWidth;
      return;
    }

    const newWidthMenubar = isWide ? '13%' : '70px';
    const newWidthMainContent = isWide ? '86%' : 'calc(100% - 85px)';
    const newDisplay = isWide ? 'block' : 'none';

    if (menubar) menubar.style.width = newWidthMenubar;
    if (mainContent) mainContent.style.width = newWidthMainContent;

    this.elements.forEach(item => {
      const elem = document.getElementById(item.menu_name_id);
      if (elem) elem.style.display = newDisplay;
    });

    this.previousWindowWidth = this.windowWidth;
  }

  activeMatProgressBar() {
    this.matProgressBarVisible = true;
    this.cdr.detectChanges();
  }

  hideMatProgressBar() {
    this.matProgressBarVisible = false;
    this.cdr.detectChanges();
  }

  openDialog(dialogTitle: string, dialogText: string, dialogType: number, navigateRoute: string | null): void {
    const dialogRef = this.dialog.open(CustomAlertComponent, {
      data: { title: dialogTitle, text: dialogText, type: dialogType }
    });

    dialogRef.afterClosed().subscribe(() => {
      if (navigateRoute) {
        window.location.href = navigateRoute;
      }
    });
  }
}

<nav class="navbar navbar-dark bg-dark pt-3 pb-3">
  <div class="d-flex align-items-center" style="margin-left: 0.5rem;">
    <fa-icon [icon]="faBars" class="me-3 cursor_pointer" style="color: white; font-size: 1.5rem;"
      (click)="OpenCloseMenu()"></fa-icon>
    <a class="navbar-brand cursor_pointer fs-4" style="margin-top: -2px;" (click)="loadHomePage()">Streaming App</a>
  </div>
</nav>


<div class="main_content">
  <div class="custom_menu bg-dark">
    <div class="custom_menu_container">
      <div *ngFor="let menu of layout">
        <div class="a_custom_menu_item cursor_pointer" id="menu_{{menu.id}}" (click)="ToggleMenu(menu)">
          <div class="custom_menu_item">
            <img src="images/a_menu_item_image.svg" class="menu_icons" />
            <span class="menu_item_text">{{menu.menu_name}}</span>
          </div>
          <fa-icon *ngIf="menu.parent_id === -1" [icon]="faChevronDown" class="menu_item_expand_icon"
            [ngClass]="{ 'rotated': menu.is_expanded }"></fa-icon>
        </div>


        <div [@submenuToggle]="menu.is_expanded ? 'expanded' : 'collapsed'">
          <div *ngFor="let sub of menu.child">
            <div class="a_custom_menu_item sub_item cursor_pointer" id="menu_{{sub.id}}" (click)="ToggleMenu(sub)">
              <div class="custom_menu_item">
                <img src="images/a_menu_item_image.svg" class="menu_icons" />
                <span class="menu_item_text">{{sub.menu_name}}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="custom_body">
    <router-outlet></router-outlet>
  </div>
</div>
