// src/Page-Components/Upload/Upload.jsx
import React, { useState, useEffect } from 'react';
import { Environment } from '../../Environment/Environment';
import AlertModal from '../Common-Components/AlertModal/AlertModal';
import './Upload.css';
import removeFile from '../../../public/Images/remove-file.svg';
import { UploadService } from '../../Service/UploadService';


let loadAlertModal = null;
function Upload() {
    const [file_not_uploaded, set_file_not_uploaded] = useState(true);
    const [video_pubblicity_status, set_video_pubblicity_status] = useState(0);
    const [video_upload_success, set_video_upload_success] = useState(false);
    const [progress, setProgress] = useState(0);
    const [thumbnail, set_thumbnail] = useState(null);
    const [thumbnail_name, set_thumbnail_name] = useState("");
    const [video_info, set_video_info] = useState(null);
    const [new_video_title, set_new_video_title] = useState("");
    const [new_video_description, set_new_video_description] = useState("");

    const [max_character_title, set_max_character_title] = useState(100);
    const [max_character_description, set_max_character_description] = useState(5000);

    const [showAlertModal, setShowAlertModal] = useState(false);
    const [headerTextOfAlertModal, setHeaderTextOfAlertModal] = useState(null);
    const [bodyTextOfAlertModal, setBodyTextOfAlertModal] = useState(null);
    const [colorOfAlertModal, setColorOfAlertModal] = useState('green');

    const uploadService = new UploadService();


    async function handleVideoUpload(event) {
        set_file_not_uploaded(false);
        document.getElementById("dropcontainer").style.height = "180px";
        let file = event.target.files[0];

        if (!file) {
            Alert(Environment.alert_modal_header_video_info_upload, Environment.colorWarning, "Please select a video file.");
            return;
        }

        const formData = new FormData();
        formData.append("video", file);

        try {
            const result = await uploadService.DoUploadVideo(formData, setProgress);

            if (result.data.status === 200) {
                set_video_upload_success(true);
                set_video_info(result.data.data);
            } else {
                Alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, "Error uploading video! (Internal server error)");
            }
        } catch (error) {
            console.error('Error uploading video:', error);
        }
    }


    function handleVideoStatusToggleSwitch() {
        const toggle = document.getElementById('video_status_toggle');

        toggle.classList.toggle('toggle-right');

        if (video_pubblicity_status === 0) {
            set_video_pubblicity_status(1);
        } else {
            set_video_pubblicity_status(0);
        }
    }


    function thumbnailSave(event) {
        const file = event.target.files[0];
        if (file) {
            set_thumbnail_name(file.name);
            set_thumbnail(file);
        }
    }


    function removeThumbnail() {
        event.preventDefault();
        set_thumbnail(null);
        set_thumbnail_name("");
    }


    async function saveVideoInfo() {
        let formData = new FormData();
        formData.append("title", new_video_title);
        formData.append("description", new_video_description);
        formData.append("is_public", parseInt(video_pubblicity_status));
        formData.append("thumbnail", thumbnail);
        formData.append("video_info", JSON.stringify(video_info));

        try {
            let response = await uploadService.DoUploadVideoInfo(formData);

            if (response.status == 200) {
                Alert(Environment.alert_modal_header_video_info_upload, Environment.colorSuccess, response.message);
            } else {
                Alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, response.message);
            }
        } catch (error) {
            console.error("Error:", error);
            Alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, "Failed to upload video info.");
        }
    }


    function Alert(header, color, message) {
        closeAlertModal();

        setColorOfAlertModal(color);
        openAlertModal(header, message);

        loadAlertModal = setTimeout(() => {
            closeAlertModal();
        }, 5000);
    }


    function openAlertModal(header_text, body_text) {
        setHeaderTextOfAlertModal(header_text);
        setBodyTextOfAlertModal(body_text);
        setShowAlertModal(true);
    }


    function closeAlertModal() {
        setShowAlertModal(false);
        setHeaderTextOfAlertModal(null);
        setBodyTextOfAlertModal(null);

        clearTimeout(loadAlertModal);
        loadAlertModal = null;
    }


    return (
        <>
            <div className='container-upload '>
                <AlertModal showModal={showAlertModal} handleClose={closeAlertModal} headerText={headerTextOfAlertModal} bodyText={bodyTextOfAlertModal} alertColor={colorOfAlertModal} />

                <form className='file-upload-form'>
                    <label className="drop-container" id="dropcontainer">
                        {file_not_uploaded && <span className="drop-title">Drop video files here</span>}
                        {file_not_uploaded && <span className="drop-or-text">or</span>}
                        {file_not_uploaded && <input type="file" accept="video/*" onChange={handleVideoUpload} required />}

                        {!file_not_uploaded &&
                            <div className='uploading-percentage-text'>
                                {!video_upload_success && <h1 class="uploading-text"></h1>}
                                {video_upload_success && <h1>Uploaded</h1>}
                                <h1>&nbsp;({progress}%)</h1>
                            </div>
                        }

                        {progress > 0 && (
                            <div className="upload_progress_bar">
                                <div className="progress_bar_container">
                                    <div className="upload_progress" style={{ width: `${progress}%` }}></div>
                                </div>
                            </div>
                        )}
                    </label>
                </form>

                <div className='title'>
                    <span>Title<span className="required_color">*</span></span>

                    <div className="input-container">
                        <input
                            type="text"
                            className="upload_input upload_normal_input"
                            id="video_title"
                            maxLength={max_character_title}
                            value={new_video_title}
                            onChange={(e) => set_new_video_title(e.target.value)}
                        />
                        <span id="charCountTitle">{new_video_title.length}/{max_character_title}</span>
                    </div>
                </div>

                <div className='description'>
                    <span>Description<span className="required_color">*</span></span>

                    <div className="input-container">
                        <textarea
                            className="upload_input upload_textarea"
                            rows="10"
                            id="video_description"
                            maxLength={max_character_description}
                            value={new_video_description}
                            onChange={(e) => set_new_video_description(e.target.value)}>
                        </textarea>
                        <span id="charCountDescription">{new_video_description.length}/{max_character_description}</span>
                    </div>
                </div>

                <div className='thumbnail_and_save'>
                    <label className="drop-container-thumbnail" id="dropcontainer">
                        {!thumbnail && <span className="drop-title">Drop thumbnail here</span>}
                        {!thumbnail && <span className="drop-or-text">or</span>}
                        {!thumbnail && <input type="file" accept="image/*" onChange={thumbnailSave} required />}
                        {thumbnail && <span className="drop-filename-text">{thumbnail_name}</span>}
                        {thumbnail && <span className='remove_thumbnail_btn'><img src={removeFile} className='menu-icons' onClick={removeThumbnail}></img></span>}
                    </label>

                    <div className='video_right_side_buttons'>
                        <div className='video_publicity_switch_container'>
                            <span className='video_publicity_name'>Private</span>
                            <div className='video_publicity_switch' onClick={handleVideoStatusToggleSwitch}>
                                <div id='video_status_toggle'></div>
                            </div>
                            <span className='video_publicity_name'>Public</span>
                        </div>

                        {video_upload_success && <button className='video-save-button' onClick={saveVideoInfo}>Save</button>}
                    </div>
                </div>
            </div>
        </>
    );
}

export default Upload;

// src/app/page-component/upload/upload.component.ts
import { Component, OnInit } from '@angular/core';
import { UploadService } from '../../service/upload/upload.service';
import { Environment } from '../../constants/environment';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule } from '@angular/material/dialog';
import { MatProgressBarModule } from '@angular/material/progress-bar';

@Component({
  selector: 'app-upload',
  imports: [CommonModule, FormsModule, MatDialogModule, MatProgressBarModule],
  standalone: true,
  templateUrl: './upload.component.html',
  styleUrls: ['./upload.component.css']
})
export class UploadComponent implements OnInit {
  fileNotUploaded = true;
  videoPublicityStatus = 0;
  videoUploadSuccess = false;
  progress = 0;
  thumbnail: File | null = null;
  thumbnailName = '';
  videoInfo: any = null;
  newVideoTitle = '';
  newVideoDescription = '';

  maxCharacterTitle = 100;
  maxCharacterDescription = 5000;

  showAlertModal = false;
  headerTextOfAlertModal: string | null = null;
  bodyTextOfAlertModal: string | null = null;
  colorOfAlertModal = 'green';

  private loadAlertModal: any = null;

  constructor(private uploadService: UploadService) {}

  ngOnInit(): void {}

  handleVideoUpload(event: any): void {
    this.fileNotUploaded = false;
    const file = event.target.files[0];

    if (!file) {
      //this.alert(Environment.alert_modal_header_video_info_upload, Environment.colorWarning, "Please select a video file.");
      return;
    }

    const formData = new FormData();
    formData.append("video", file);

    this.uploadService.DoUploadVideo(formData, (progress: number) => {
      this.progress = progress;
    }).subscribe({
      next: (result: any) => {
        if (result.status === 200) {
          this.videoUploadSuccess = true;
          this.videoInfo = result.data;
        } else {
          //this.alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, "Error uploading video! (Internal server error)");
        }
      },
      error: () => {
        console.error("Error uploading video");
      }
    });
  }

  handleVideoStatusToggleSwitch(): void {
    this.videoPublicityStatus = this.videoPublicityStatus === 0 ? 1 : 0;
  }

  thumbnailSave(event: any): void {
    const file = event.target.files[0];
    if (file) {
      this.thumbnailName = file.name;
      this.thumbnail = file;
    }
  }

  removeThumbnail(event: Event): void {
    event.preventDefault();
    this.thumbnail = null;
    this.thumbnailName = "";
  }

  saveVideoInfo(): void {
    const formData = new FormData();
    formData.append("title", this.newVideoTitle);
    formData.append("description", this.newVideoDescription);
    formData.append("is_public", this.videoPublicityStatus.toString());
    if (this.thumbnail) formData.append("thumbnail", this.thumbnail);
    formData.append("video_info", JSON.stringify(this.videoInfo));

    this.uploadService.DoUploadVideoInfo(formData).subscribe({
      next: (response: any) => {
        if (response.status === 200) {
          //this.alert(Environment.alert_modal_header_video_info_upload, Environment.colorSuccess, response.message);
        } else {
          //this.alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, response.message);
        }
      },
      error: () => {
        //this.alert(Environment.alert_modal_header_video_info_upload, Environment.colorError, "Failed to upload video info.");
      }
    });
  }

  alert(header: string, color: string, message: string): void {
    this.closeAlertModal();
    this.colorOfAlertModal = color;
    this.openAlertModal(header, message);

    this.loadAlertModal = setTimeout(() => {
      this.closeAlertModal();
    }, 5000);
  }

  openAlertModal(header: string, body: string): void {
    this.headerTextOfAlertModal = header;
    this.bodyTextOfAlertModal = body;
    this.showAlertModal = true;
  }

  closeAlertModal(): void {
    this.showAlertModal = false;
    this.headerTextOfAlertModal = null;
    this.bodyTextOfAlertModal = null;
    clearTimeout(this.loadAlertModal);
    this.loadAlertModal = null;
  }
}

<mat-progress-bar mode="indeterminate" *ngIf="matProgressBarVisible" class="matProgressBar"></mat-progress-bar>

<div class="container">
    <h3 class="text-muted mb-3 container_header">Upload Video</h3>

    <form class="mb-4">
        <div class="mb-3 border border-dashed p-4 text-center rounded" id="dropcontainer">
            <div class="border rounded p-4 text-center" *ngIf="fileNotUploaded" [class.bg-light]="isDragOver"
                (dragover)="onDragOver($event)" (dragleave)="onDragLeave($event)" (drop)="onFileDrop($event)">
                <div>
                    <p class="text-muted fw-bold">Drop video files here</p>
                    <p class="text-muted">or</p>
                    <input type="file" accept=".mp4" (change)="handleVideoUpload($event)"
                        class="form-control w-auto mx-auto" required />
                </div>
            </div>


            <div *ngIf="!fileNotUploaded" class="text-center">
                <h5 *ngIf="!videoUploadSuccess" class="text-primary">Uploading...</h5>
                <h5 *ngIf="videoUploadSuccess" class="text-success">Uploaded</h5>
                <h5>&nbsp;({{progress}}%)</h5>
            </div>

            <div *ngIf="progress > 0" class="progress mt-3">
                <div class="progress-bar" role="progressbar" [style.width.%]="progress" aria-valuemin="0"
                    aria-valuemax="100">{{progress}}%</div>
            </div>
        </div>
    </form>

    <div class="mb-4">
        <label class="form-label fw-semibold">Video Title<span class="text-danger">*</span></label>
        <div class="input-group">
            <input type="text" class="form-control" id="video_title" [maxLength]="maxCharacterTitle"
                [(ngModel)]="newVideoTitle" name="title" />
        </div>
        <small class="form-text text-muted">{{newVideoTitle.length}} / {{maxCharacterTitle}}</small>
    </div>

    <div class="mb-4">
        <label class="form-label fw-semibold">Video Description<span class="text-danger">*</span></label>
        <div class="input-group">
            <textarea class="form-control" rows="5" id="video_description" [maxLength]="maxCharacterDescription"
                [(ngModel)]="newVideoDescription" name="description"></textarea>
        </div>
        <small class="form-text text-muted">{{newVideoDescription.length}} / {{maxCharacterDescription}}</small>
    </div>

    <div class="card p-3 position-relative mb-4">
        <div class="d-flex justify-content-between">
            <label class="form-label fw-semibold">Enter tags (comma-separated):</label>
            <small class="text-muted" style="font-size: 0.8rem;">
                {{ tagInput.length }}/500
            </small>
        </div>

        <textarea class="form-control" rows="5" id="tagInput" [maxLength]="500" (input)="onInputChange()"
            [(ngModel)]="tagInput" placeholder="e.g., Gaming, Video Game, Gaming Community"></textarea>

        <div class="mt-3 d-flex flex-wrap gap-2">
            <span *ngFor="let tag of tags; let i = index"
                class="badge bg-secondary px-3 py-2 d-flex align-items-center">
                {{ tag }}
                <button type="button" class="btn-close btn-close-white ms-2" aria-label="Remove"
                    (click)="removeTag(i)"></button>
            </span>
        </div>
    </div>

    <div class="d-flex flex-row align-items-center flex-md-row justify-content-between align-items-start gap-4 w-100">
        <!-- Thumbnail Upload -->
        <div class="border border-dashed p-3 rounded text-center w-50" [class.bg-light]="isThumbnailDragOver"
            (dragover)="onThumbnailDragOver($event)" (dragleave)="onThumbnailDragLeave($event)"
            (drop)="onThumbnailDrop($event)">
            <div *ngIf="!thumbnail">
                <p class="fw-bold text-muted">Drop thumbnail here</p>
                <p class="text-muted">or</p>
                <input type="file" accept=".jpg, .jpeg, image/jpeg" (change)="thumbnailSave($event)"
                    class="form-control" required />
            </div>

            <div *ngIf="new_thumbnail_base64 !== null || new_thumbnail_base64 !== ''"
                class="w-100 d-flex flex-column align-items-center gap-2">
                <img [src]="new_thumbnail_base64" class="img-fluid rounded mb-3 w-25" />
            </div>

            <div *ngIf="thumbnail" class="d-flex flex-column align-items-center gap-2">
                <span class="text-success">{{thumbnailName}}</span>
                <div class="d-flex flex-row-reverse w-100">
                    <button class="btn btn-outline-secondary btn-sm" (click)="removeThumbnail($event)">
                        <fa-icon [icon]="faTrash"></fa-icon>
                        Remove
                    </button>
                </div>
            </div>
        </div>

        <!-- Switch + Save Button -->
        <div
            class="d-flex flex-column align-items-center gap-3 align-items-center border border-dashed p-3 rounded w-25">
            <label>Visibility Status</label>
            <div class="form-check form-switch">
                <input type="checkbox" class="form-check-input" id="video_status_toggle"
                    (change)="handleVideoStatusToggleSwitch()" [checked]="videoPublicityStatus === 1" />
                <label class="form-check-label" for="video_status_toggle">
                    {{ videoPublicityStatus === 1 ? 'Public' : 'Private' }}
                </label>
            </div>

            <div class="d-flex flex-row-reverse mt-3">
                <button *ngIf="videoUploadSuccess" [disabled]="matProgressBarVisible" class="btn btn-sm btn-primary"
                    (click)="saveVideoInfo()">Save</button>
            </div>
        </div>
    </div>
</div>
